spring.application.name=livepoll-backend
spring.security.oauth2.client.registration.google.client-id=747373399094-rra9pv35dufhkgdbvdbvodmnsqgg3ofp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile